/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * F1 Dashboard API
 * The F1 Dashboard API description
 * OpenAPI spec version: 1.0
 */
export interface DriverDto {
  /** Unique identifier for the driver */
  driverId: string;
  /** Permanent number of the driver */
  permanentNumber?: string;
  /** Driver code (e.g., ALO for Alonso) */
  code?: string;
  /** URL to driver's Wikipedia page */
  url: string;
  /** Driver's given name */
  givenName: string;
  /** Driver's family name */
  familyName: string;
  /** Driver's date of birth */
  dateOfBirth: string;
  /** Driver's nationality */
  nationality: string;
}

export interface SeasonDto {
  /** The year of the F1 season */
  year: number;
  /** The URL to the season details */
  url: string;
  /** The ID of the driver who won the season */
  winnerDriverId?: string;
  /** The driver who won the season */
  winner?: DriverDto;
}

export interface RaceDto {
  /** Unique identifier for the race */
  id: string;
  /** The season year */
  season: number;
  /** The round number in the season */
  round: number;
  /** Name of the race */
  raceName: string;
  /** Name of the circuit */
  circuitName: string;
  /** Date of the race */
  date: string;
  /** Time of the race */
  time?: string;
  /** URL to race details */
  url?: string;
  /** ID of the winning driver */
  winnerDriverId?: string;
  /** ID of the winning constructor */
  winnerConstructorId?: string;
  /** Winning time */
  winnerTime?: string;
  /** Number of laps completed by winner */
  winnerLaps?: number;
  /** Starting grid position of winner */
  winnerGrid?: number;
  /** Points earned by winner */
  winnerPoints?: number;
  /** The driver who won the race */
  winnerDriver?: DriverDto;
}

