/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * F1 Dashboard API
 * The F1 Dashboard API description
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  RaceDto
} from '../f1DashboardAPI.schemas';





/**
 * @summary Get all races for a specific season
 */
export const racesControllerFindBySeason = (
    season: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RaceDto[]>> => {
    
    
    return axios.default.get(
      `/races/season/${season}`,options
    );
  }


export const getRacesControllerFindBySeasonQueryKey = (season: number,) => {
    return [`/races/season/${season}`] as const;
    }

    
export const getRacesControllerFindBySeasonQueryOptions = <TData = Awaited<ReturnType<typeof racesControllerFindBySeason>>, TError = AxiosError<unknown>>(season: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof racesControllerFindBySeason>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRacesControllerFindBySeasonQueryKey(season);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof racesControllerFindBySeason>>> = ({ signal }) => racesControllerFindBySeason(season, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(season), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof racesControllerFindBySeason>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RacesControllerFindBySeasonQueryResult = NonNullable<Awaited<ReturnType<typeof racesControllerFindBySeason>>>
export type RacesControllerFindBySeasonQueryError = AxiosError<unknown>


export function useRacesControllerFindBySeason<TData = Awaited<ReturnType<typeof racesControllerFindBySeason>>, TError = AxiosError<unknown>>(
 season: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof racesControllerFindBySeason>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof racesControllerFindBySeason>>,
          TError,
          Awaited<ReturnType<typeof racesControllerFindBySeason>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRacesControllerFindBySeason<TData = Awaited<ReturnType<typeof racesControllerFindBySeason>>, TError = AxiosError<unknown>>(
 season: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof racesControllerFindBySeason>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof racesControllerFindBySeason>>,
          TError,
          Awaited<ReturnType<typeof racesControllerFindBySeason>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRacesControllerFindBySeason<TData = Awaited<ReturnType<typeof racesControllerFindBySeason>>, TError = AxiosError<unknown>>(
 season: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof racesControllerFindBySeason>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all races for a specific season
 */

export function useRacesControllerFindBySeason<TData = Awaited<ReturnType<typeof racesControllerFindBySeason>>, TError = AxiosError<unknown>>(
 season: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof racesControllerFindBySeason>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRacesControllerFindBySeasonQueryOptions(season,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



